export const GET_CRIPTOS = "GET_CRIPTOS";
export const GET_CRIPTOS_TOTAL = "GET_CRIPTOS_TOTAL";
export const SEARCH_CRIPTOS = "SEARCH_CRIPTOS"; 
export const GET_CRIPTO_ONLY = "GET_CRIPTO_ONLY";
export const FAVORITOS = "FAVORITOS";